[versions]
junit-jupiter-engine = "5.12.1"
compose = "1.7.3"
coroutines = "1.10.1"

[libraries]
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit-jupiter-engine" }
coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines"}

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version = "2.2.21" }
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version = "2.2.21" }
